{{- if and .Values.jibri.enabled (not .Values.jibri.useExternalJibri) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
  {{- with .Values.jibri.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.jibri.replicaCount | default 1 }}
  {{- if .Values.jibri.strategy }}
  strategy: {{- toYaml .Values.jibri.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.jibri.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jibri.selectorLabels" . | nindent 8 }}
      {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.jibri.podLabels }}
        {{ $label }}: {{ $value }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jibri/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/jibri/xmpp-secret.yaml") . | sha256sum }}
      {{- range $annotation, $value := mergeOverwrite .Values.global.podAnnotations .Values.jibri.podAnnotations }}
        {{ $annotation }}: {{ $value|quote }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        image: "{{ .Values.jibri.image.repository }}:{{ default .Chart.AppVersion .Values.jibri.image.tag }}"
        imagePullPolicy: {{ pluck "pullPolicy" .Values.jibri.image .Values.image | first }}
        ports:
        - name: http-internal
          containerPort: 3333
        - name: http-api
          containerPort: 2222
        {{- with default .Values.jibri.livenessProbe .Values.jibri.livenessProbeOverride }}
        livenessProbe:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with default .Values.jibri.readinessProbe .Values.jibri.readinessProbeOverride }}
        readinessProbe:
        {{- toYaml . | nindent 10 }}
        {{- end }}

        envFrom:
        - secretRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jibri
        - configMapRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-common
        - configMapRef:
            name: {{ include "jitsi-meet.jibri.fullname" . }}

        {{- if (gt (int .Values.jibri.replicaCount) 1) }}
        # Set Jibri Instance ID based on pod name:
        env:
        - name: JIBRI_INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- end }}

        resources:
          {{- toYaml .Values.jibri.resources | nindent 12 }}

        volumeMounts:
        - name: jibri-data
          mountPath: /data
        {{- if .Values.jibri.shm.enabled }}
        - name: dev-shm
          mountPath: /dev/shm
        {{- end }}

      volumes:
      - name: jibri-data
        {{- if .Values.jibri.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.jibri.persistence.existingClaim | default (include "jitsi-meet.jibri.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.jibri.shm.enabled }}
      - name: dev-shm
      {{-   if .Values.jibri.shm.useHost }}
        hostPath:
          path: /dev/shm
      {{-   else }}
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.jibri.shm.size | default "256Mi" | quote }}
      {{-   end }}
      {{- end }}
{{- end }}
