{{- if or (and (kindIs "invalid" .Values.jvb.service.enabled) (not (or .Values.jvb.useHostPort .Values.jvb.useHostNetwork))) .Values.jvb.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.jvb.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jvb.service.type }}
  {{- with .Values.jvb.service.LoadbalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ default 10000 .Values.jvb.UDPPort }}
      {{- if and .Values.jvb.nodePort (or (eq .Values.jvb.service.type "NodePort") (eq .Values.jvb.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.jvb.nodePort }}
      {{- end }}
      protocol: UDP
      name: rtp-udp
    - port: 4443  # Add this section to include TCP port 4443
      {{- if and .Values.jvb.nodePort (or (eq .Values.jvb.service.type "NodePort") (eq .Values.jvb.service.type "LoadBalancer")) }}
      nodePort: 4443  # Add this line to specify the nodePort for TCP 4443 if needed
      {{- end }}
      protocol: TCP  # Specify TCP as the protocol
      name: custom-tcp-port  # Choose a name for the port
  {{- with .Values.jvb.service.externalIPs }}
  externalIPs:
  {{ toYaml . | indent 2 | trim }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.jvb.service.externalTrafficPolicy }}
  selector:
    {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 4 }}
{{- end }}
