{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "jitsi-meet.web.fullname" . -}}
{{- $svcPort := .Values.web.service.port -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
  {{- if or .Values.web.ingress.annotations (and .Values.web.ingress.ingressClassName (semverCompare "<1.19-0" $kubeVersion)) }}
  annotations:
    {{- if and .Values.web.ingress.ingressClassName (semverCompare "<1.19-0" $kubeVersion) }}
    kubernetes.io/ingress.class: {{ .Values.web.ingress.ingressClassName }}
    {{- end }}
    {{- with .Values.web.ingress.annotations }}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
{{- if and .Values.web.ingress.ingressClassName (semverCompare ">=1.19-0" $kubeVersion) }}
  ingressClassName: {{ .Values.web.ingress.ingressClassName }}
{{- end }}
{{- if .Values.web.ingress.tls }}
  tls:
  {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
            {{ if semverCompare ">=1.19-0" $kubeVersion }}
              service:
                name: {{ $fullName }}
                port:
                  {{ if kindIs "float64" $svcPort }}
                  number: {{ $svcPort }}
                  {{ else }}
                  name: {{ $svcPort }}
                  {{ end }}
            {{ else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{ end }}
        {{- end }}
  {{- end }}
{{- end }}
